github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Pre-load docker image to workspace 
    command: materialize/materialized:v0.26.4
    command: ysql/mysql-server:8.0.27
    command: confluentinc/cp-zookeeper:7.2.0
    command: confluentinc/cp-kafka:7.2.0
    command: confluentinc/cp-schema-registry:7.2.0
    command: debezium/connect:1.8
    command: materialize/cli:v0.26.4
    command: metabase/metabase:v0.41.5

  - name: Install docker-compose version 2.4.1 
    command: sudo curl -SL https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

# ports:
    
  # Confluent Server (broker)
  # - port: 9092
  #   onOpen: ignore
    
  # Confluent Server (REST)
  # - port: 8090
  #   onOpen: ignore
    
  # Schema Registry
  # - port: 8081
  #   onOpen: ignore
  # - port: 8082
  #   onOpen: ignore
    
  # Kafka Connect
  # - port: 8083
  #   onOpen: ignore

